export const RoutePath = {
  MAIN: "/",
  RULE_CHOOSE: "/rule-choose",
  REGISTER: "/register",
  QR: "/qr",
  RECONFIRM_QR: "/reconfirm-qr",
  INTRODUCE: "/introduce",
  EVENT: "/event",
  EVENT_GROUP: "/event-group",
  EVENT_STAGE: "/event-stage",
  MISSION: "/mission",
  STEP: "/step/:purpose",
  NOTFOUND: "*",
  ZEROGAME: "/zerogame",
};

export const Booth = {
  10: "요원 지원 대기소",
  11: "대결! 체력 테스트",
  12: "사격 훈련",
  13: "페달을 밟아라!",
  20: "현장 출동 대기소",
  21: "틀린 그림 찾기 1",
  22: "틀린 그림 찾기 2",
  23: "틀린 그림 찾기 3",
  24: "틀린 그림 찾기 4",
  30: "기후 위기 피난소",
  31: "대결! 지구 한 번 굴려볼링?",
  32: "대결! 빙하에서 살아남기",
  40: "결전 대기소",
  41: "환경, 유퀴즈!",
  42: "쓰봉이의 문단속",
  43: "대결! 쉘위 탭댄스",
};
